#!/usr/bin/env bash
set -x
script_dir="$(cd "$(dirname "$0")"; pwd;)";
export EDITOR=nano

###############################################################################
# Time
###############################################################################

ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
hwclock --systohc --utc

###############################################################################
# Language
###############################################################################

echo "en_GB.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo LANG=en_GB.UTF-8 >> /etc/locale.conf
echo KEYMAP=uk >> /etc/vconsole.conf

###############################################################################
# Hostname
###############################################################################

echo archlinux-desktop >> /etc/hostname

###############################################################################
# Bootloader
###############################################################################

grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

###############################################################################
# Configure accounts
###############################################################################

passwd

useradd -m -G wheel oliver
passwd oliver

echo >> /etc/sudoers
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

echo >> /etc/sudoers
echo "# Allow all local users to change screen brightness" >> /etc/sudoers
echo "ALL $(cat /etc/hostname) = (root) NOPASSWD: /usr/bin/xbacklight" >> /etc/sudoers

###############################################################################
# Cleanup
###############################################################################

rm /root/chroot
