#!/usr/bin/env bash
set -ex
script_dir="$(cd "$(dirname "$0")"; pwd;)";

###############################################################################
# Create directories
###############################################################################

mkdir -p ~/git
mkdir -p ~/screenshots

###############################################################################
# Deploy config files
###############################################################################

cd ~/git
git clone https://github.com/ow97/config
git clone https://github.com/ow97/arch

ln -sf ~/git/config/bash ~/.bashrc

ln -sf ~/git/config/xinitrc ~/.xinitrc

ln -sf ~/git/config/latexmkrc ~/.latexmkrc

ln -sf ~/git/config/compton ~/.compton.conf

mkdir -p ~/.config/i3
ln -sf ~/git/config/i3 ~/.config/i3/config

mkdir -p ~/.config/i3blocks
ln -sf ~/git/config/i3blocks ~/.config/i3blocks/config

mkdir -p ~/.config/termite
ln -sf ~/git/config/termite ~/.config/termite/config

mkdir -p ~/.config/redshift
ln -sf ~/git/config/redshift ~/.config/redshift/redshift.conf

mkdir -p ~/.config/fontconfig
ln -sf ~/git/config/fonts ~/.config/fontconfig/fonts.conf

mkdir -p ~/.config/nano
ln -sf ~/git/config/nano ~/.config/nano/nanorc

sudo ln -sf ~/git/config/pacman /etc/pacman.conf

###############################################################################
# Configure git
###############################################################################

git config --global user.email "ow97@users.noreply.github.com"
git config --global user.name "ow97"

# Enable chromium flags
#   - Override software rendering list
#   - GPU rasterization
#   - Zero-copy rasterizer
