#!/usr/bin/env bash
set -ex
script_dir="$(cd "$(dirname "$0")"; pwd;)";

###############################################################################
# Install packages
###############################################################################

# Official repos
pacman -Syy
xargs pacman --needed --noconfirm -S < "$script_dir/packages"

# Install pikaur
cd /tmp
git clone https://github.com/actionless/pikaur
cd pikaur
pacman -S --needed --noconfirm --asdeps pyalpm base-devel
python3 ./pikaur.py -S --noconfirm pikaur
cd /tmp

# Add keys
gpg --recv-keys 4E2C6E8793298290 # tor-browser

# Install AUR packages
xargs pikaur --noconfirm -S < "$script_dir/aur_packages"

# Cleanup dependencies
pacman -Qtdq | pacman --noconfirm -Rns - || true

###############################################################################
# Setup services
###############################################################################

systemctl enable wicd.service

###############################################################################
# Setup users
###############################################################################

sudo -u oliver oliver

###############################################################################
# Complete setup
###############################################################################

sudo reboot
